library(Rscclust)
context("nng_clustering.R (types)")

source("../replica/replica_findseed.R", local = TRUE)
source("../replica/replica_make_nng.R", local = TRUE)
source("../replica/replica_nng.R", local = TRUE)
source("utils_nng.R", local = TRUE)


test_that("type nng clustering function cluster correctly.", {

  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 3L, "1" = 3L, "2" = 3L, "3" = 3L),
                                 12L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 0L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "inwards_order",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "inwards_order",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "exclusion_order",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "exclusion_order",
                                 "ignore",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "inwards_order",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "inwards_order",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "exclusion_order",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "exclusion_order",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "lexical",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 0L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "inwards_order",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "inwards_order",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "exclusion_order",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "exclusion_order",
                                 "ignore",
                                 type_test_radius,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "lexical",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "inwards_order",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "inwards_order",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 5L,
                                 "exclusion_order",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "exclusion_order",
                                 "ignore",
                                 type_test_radius,
                                 main_data_points,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "closest_assigned",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "closest_seed",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "estimated_radius_closest_seed",
                                 NULL,
                                 NULL,
                                 "ignore",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "closest_assigned",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "closest_seed",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "estimated_radius_closest_seed",
                                 NULL)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "closest_assigned",
                                 test_radius)
  test_nng_types_against_replica(test_distances1,
                                 types1,
                                 c("0" = 1L, "1" = 2L, "2" = 1L, "3" = 1L),
                                 10L,
                                 "lexical",
                                 "ignore",
                                 NULL,
                                 main_data_points,
                                 "closest_seed",
                                 test_radius)
})
